name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.16', '1.17']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Go dependencies
        run: go mod download
        env:
          GOPROXY: "https://proxy.golang.org"

      - name: Lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.44

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
